import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import auditRouter from "./audit";
import membersRouter from "./members";
import memberGroupsRouter from "./member-groups";
import visitorsRouter from "./visitors";
import financeRouter from "./finance";
import teachingRouter from "./teaching";
import eventsRouter from "./events";
import lgpdRouter from "./lgpd";
import utilsRouter from "./utils";
import storageRouter from "./storage";
import mediaRouter from "./media";
import ministriesRouter from "./ministries";
import assetsRouter from "./assets";
import schedulesRouter from "./schedules";
import dashboardRouter from "./dashboard";
import planningRouter from "./planning";
import discipleshipRouter from "./discipleship";
import contentsRouter from "./contents";
import pastoralRouter from "./pastoral";
import counselingRouter from "./counseling";
import songsRouter from "./songs";
import cultosRouter from "./cultos";
import articlesRouter from "./articles";
import forumRouter from "./forum";
import institutionalRouter from "./institutional";
import pixRouter from "./pix";
import notificationsRouter from "./notifications";
import councilRouter from "./council";
import accountsRouter from "./accounts";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/dashboard", dashboardRouter);
router.use("/auth", authRouter);
router.use("/admin/accounts", accountsRouter);
router.use("/audit", auditRouter);
router.use("/members", membersRouter);
router.use("/member-groups", memberGroupsRouter);
router.use("/visitors", visitorsRouter);
router.use("/finance", financeRouter);
router.use("/teaching", teachingRouter);
router.use("/events", eventsRouter);
router.use("/lgpd", lgpdRouter);
router.use("/media", mediaRouter);
router.use("/ministries", ministriesRouter);
router.use("/assets", assetsRouter);
router.use("/schedules", schedulesRouter);
router.use("/planning", planningRouter);
router.use("/discipleship", discipleshipRouter);
router.use("/contents", contentsRouter);
router.use("/pastoral", pastoralRouter);
router.use("/counseling", counselingRouter);
router.use("/songs", songsRouter);
router.use("/cultos", cultosRouter);
router.use("/articles", articlesRouter);
router.use("/forum", forumRouter);
router.use("/pages", institutionalRouter);
router.use("/pix", pixRouter);
router.use("/notifications", notificationsRouter);
router.use("/council", councilRouter);
router.use("/utils", utilsRouter);
router.use(storageRouter);

export default router;
